time_to_send: "08:00"
telegram:
  chat_id: 0
  token_id: ""
traffic:
  url: ""
weather:
  lat: 0.000
  lon: 0.000
  time: "09:00-20:00"
  timezone: "Asia/Vladivostok"
task:
  calendarid: ""
  clientsecret: "client_secret.json"
  token: "token.json"